[package]
name = "tokio-leak-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
leak-playground = { version = "0.1.0", path = "..", features = ["tokio_rt"] }
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread"] }
