[package]
name = "leak-playground-tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
leak-playground-std = { version = "0.1.0", path = "../std", features = ["tokio_rt"] }
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread"] }
