[workspace]
members = ["tokio"]

[package]
name = "leak-playground"
version = "0.1.0"
edition = "2021"

[features]
tokio = ["dep:tokio"]
tokio_rt = ["tokio", "tokio/rt"]

[dependencies]
tokio = { version = "1.35.1", optional = true }
